export enum AUTH_ACTIONS {
  SET_TOKEN = 'SET_TOKEN',
  SET_ACCOUNT = 'SET_ACCOUNT',
  GET_ACCOUNT_REQUEST = 'GET_ACCOUNT_REQUEST',
  GET_ACCOUNT_ERROR = 'GET_ACCOUNT_ERROR',
  SET_ACCOUNT_LOADING = 'SET_ACCOUNT_LOADING',
  SET_CURRENT_ROLE = 'SET_CURRENT_ROLE',
}
